### ISSUE TITLE
Mod not showing in game

### ISSUE THREAD

**Issue by Yappieyap** [LifePlayMods/rdl_timber#1]
Hey mate how do I get your mod to work? I’ve transferred the timber folder into modules but it’s not coming up as an available mod in the in game mod settings

**Comment by rondlite** [comment]
Sorry for the late reply, this issue was reported on discord too and I have fixed it since, please check you have the latest version
(it was due to the build process not making proper windows text file encoding)

**Comment by rondlite** [comment]
Fixed
